### ISSUE TITLE
package-server.zokka-lang.com/all-packages is not up anymore

### ISSUE THREAD

**Issue by just-maiyak** [Zokka-Dev/zokka-compiler#21]
**Quick Summary:** the zokka package server is down and serves 503

## Additional Details

I'm not sure how to workaround this one

**Comment by changlinli** [comment]
Oh no! My apologies let me take a look

**Comment by changlinli** [comment]
@just-maiyak this should be fixed now! My apologies. We needed to send our website host more money :). We unfortunately don't have issues set to alert our members which I've changed now.

Also for future reference if, the main repo is down, you can always remove it from `$ELM_HOME/0.19.1/zokka/custom-package-repository-config.json` or substitute your own running server (which you can find at https://github.com/Zokka-Dev/zokka-custom-package-server)

Again apologies about this! We try to ensure we always have a one week turnaround on issues so this is technically within our turnaround time, but it was a simple enough issue to resolve that I hope these kinds of things can be resolved sooner.

**Comment by just-maiyak** [comment]
No problem, thanks for looking into it 🙂
